---
title: "envios_postales"
output: html_document
---
# Envíos Postales


```{r fig.height = fig_height_small, fig.cap=caption}

caption <- glue("Cartas Enviadas {FECHA_TITULO_FLUJO}")
## columnas CF y C
operadores <- importar_totales_trafico("C") %>%
  flujo_semestral() %>%
  mutate(numeric = numeric/1e6,
         operador="PJH")

pjh <- importar_totales_trafico("CF", header_row = 3) %>%
  flujo_semestral() %>%
  mutate(numeric = numeric/1e6,
         operador="Operadores")

bind_rows(operadores, pjh) %>% 
  arrange(year, semester, operador) %>% 
  mutate(fecha = glue("'{year  %% 100}-{semester}")) %>% 
  group_by(fecha) %>% 
  mutate(y_pos = dplyr::lag(numeric, default = 0) + numeric/2) %>% 
  ungroup() %>% 
  ggplot(aes(fecha, numeric, fill=fct_infreq(operador))) + 
  geom_col(position=position_stack(reverse=TRUE)) +
  geom_text(aes(label=scales::number_format(accuracy=1)(numeric), y=y_pos),
            color="white") + 
  scale_fill_manual("", values=c( paleta_cats[["rojo"]], pal[5])) +
  labs(x="", y="", caption="Millones de cartas") +
  guides(fill = guide_legend(direction="horizontal")) + 
  theme(legend.position = c("top"),
        plot.caption = element_text(vjust=6, hjust=0),
        axis.text.x    = ggplot2::element_text(vjust=6))
```


```{r fig.height = fig_height_small, fig.cap=caption}

caption <- "Paquetes Enviados"
## ED
importar_totales_trafico("ED", header_row = 3) %>%
  flujo_semestral() %>%
  mutate(numeric = numeric/1e3) %>%
  serie_historica_semestral_flujo(numeric) + 
  labs(x="Semestre", y="Miles")
```



```{r fig.cap=caption}

caption <- "Envíos Postales (en millones)"
## EG
importar_totales_trafico("EG", header_row = 3) %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e6) %>%
  serie_historica_semestral_flujo(numeric)

```


```{r fig.cap=caption}
## FD
caption <- "Cartas del SPU (millones)"
importar_totales_trafico("FD") %>%
 flujo_semestral() %>%
  mutate(numeric=numeric/1e6) %>%
  serie_historica_semestral_flujo(numeric)
```


```{r fig.cap=caption}
caption <- "Paquetes del SPU (miles)"
## FC
importar_totales_trafico("FC") %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e3) %>%
  serie_historica_semestral_flujo(numeric)
```


```{r fig.cap=caption}
caption <- "Envíos del SPU (millones)"
## FB
importar_totales_trafico("FB") %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e6) %>%
  serie_historica_semestral_flujo(numeric)
```


```{r fig.cap=caption}
## H
caption <- "Total semestral de Cartas Nacionales (en millones)"
importar_totales_trafico("CA")  %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e6) %>%
  serie_historica_semestral_flujo(numeric)

```


```{r fig.cap=caption}
## CB
caption <- "Salida de Cartas Internacionales (en miles)"
importar_totales_trafico("CB")  %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e3) %>%
  serie_historica_semestral_flujo(numeric)
```

```{r fig.cap=caption}
caption <- "Entrada de Cartas Internacionales (en miles)"
## CD
importar_totales_trafico("CC")  %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e3) %>%
  serie_historica_semestral_flujo(numeric)
```

```{r fig.cap=caption}
caption <- "Paquetes Nacionales (en miles)"
## DZ
importar_totales_trafico("DZ")  %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e3) %>%
  serie_historica_semestral_flujo(numeric)
```

```{r fig.cap=caption}
caption <- "Salida de Paquetes Internacionales (en miles)"
## EA
importar_totales_trafico("EA")  %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e3) %>%
  serie_historica_semestral_flujo(numeric)
```

```{r fig.cap=caption}
caption <- "Entrada de Paquetes Internacionales (en miles)"
## EB
importar_totales_trafico("EB")  %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e3) %>%
  serie_historica_semestral_flujo(numeric)
```

```{r fig.cap=caption}
caption <- glue("Composición de Cartas {FECHA_TITULO_FLUJO}")
importar_totales_trafico(c("CA", "CB", "CC")) %>%
  filter(year(fecha)==2020, semester(fecha)==1) %>%
  group_by(cabezal) %>%
  summarize(numeric=round(sum(numeric))) %>% 
  barras_horizontales(numeric, cabezal)
```

```{r fig.cap=caption}
caption <- glue("Composición de Paquetes {FECHA_TITULO_FLUJO}")
## DZ-EB
importar_totales_trafico(c("DZ", "EA", "EB")) %>%
  filter(year(fecha)==2020, semester(fecha)==1) %>%
  group_by(cabezal) %>%
  summarize(numeric=round(sum(numeric))) %>% 
  barras_horizontales(numeric, cabezal)
```

```{r fig.cap=caption}
caption <- glue("Cartas Nacionales {FECHA_TITULO_FLUJO}")
importar_totales_trafico(c("H", "W", "AL", "BA", "BP"),
                         header_row = list("cabezal_1"=3, "cabezal_2"=4)) %>%
    filter(year(fecha)==2020, semester(fecha)==1) %>%
    filter(cabezal_2=="TOTAL") %>%
    group_by(cabezal_1) %>%
    summarize(numeric=round(sum(numeric))) %>%
    barras_horizontales(numeric, cabezal_1)

```


```{r fig.cap=caption}
caption <- glue("Salida de Cartas Internacionales {FECHA_TITULO_FLUJO}")
importar_totales_trafico(c("BU", "BF", "AQ", "AB", "M"),
                         header_row = list("cabezal_1"=3, "cabezal_2"=4)) %>%
    filter(year(fecha)==2020, semester(fecha)==1) %>%
    filter(cabezal_2=="TOTAL") %>%
    group_by(cabezal_1) %>%
    summarize(numeric=round(sum(numeric))) %>%
    barras_horizontales(numeric, cabezal_1)
```

```{r fig.cap=caption}
caption <- glue("Entrada de Cartas Internacionales {FECHA_TITULO_FLUJO}")
importar_totales_trafico(c("R", "AG", "AV", "BK", "BZ"),
                         header_row = list("cabezal_1"=3, "cabezal_2"=4)) %>%
    filter(year(fecha)==2020, semester(fecha)==1) %>%
    filter(cabezal_2=="TOTAL") %>%
    group_by(cabezal_1) %>%
    summarize(numeric=round(sum(numeric))) %>%
    barras_horizontales(numeric, cabezal_1)
```

```{r fig.cap=caption}
caption <- glue("Paquetes Nacionales {FECHA_TITULO_FLUJO}")
importar_totales_trafico(c("CR", "DA", "DJ", "DS"),
                         header_row = list("cabezal_1"=3, "cabezal_2"=4)) %>%
    filter(year(fecha)==2020, semester(fecha)==1) %>%
    filter(cabezal_2=="TOTAL") %>%
    group_by(cabezal_1) %>%
    summarize(numeric=round(sum(numeric))) %>%
    filter(numeric > 0) %>%
    barras_horizontales(numeric, cabezal_1)

```


```{r fig.cap=caption}
caption <- glue("Salida de Paquetes Internacionales {FECHA_TITULO_FLUJO}")
importar_totales_trafico(c("CL", "CU", "DD", "DM", "DV"),
                         header_row = list("cabezal_1"=3, "cabezal_2"=4)) %>%
    filter(year(fecha)==2020, semester(fecha)==1) %>%
    filter(cabezal_2=="TOTAL") %>%
    group_by(cabezal_1) %>%
    summarize(numeric=round(sum(numeric))) %>%
    barras_horizontales(numeric, cabezal_1)
```

```{r fig.cap=caption}

caption <- glue("Entrada de Paquetes Internacionales {FECHA_TITULO_FLUJO}")
importar_totales_trafico(c("CX", "DG", "DP", "DY"),
                         header_row = list("cabezal_1"=3, "cabezal_2"=4)) %>%
    filter(year(fecha)==2020, semester(fecha)==1) %>%
    filter(cabezal_2=="TOTAL") %>%
    group_by(cabezal_1) %>%
    summarize(numeric=round(sum(numeric))) %>%
    barras_horizontales(numeric, cabezal_1)
```



```{r fig.height = fig_height_extra_small, fig.cap=caption}

caption <- "Total semestral de Cartas Comunes Nacionales (en millones)"
importar_totales_trafico("H") %>%
  flujo_semestral() %>%
  mutate(numeric=numeric/1e6) %>%
  serie_historica_semestral_flujo(numeric)
```
