---
title: "Informe Mercado de Servicios Postales"
author: "URSEC"
output:
  pagedown::html_paged:
    toc: true
    number_sections: false
    toc_depth: 2
    css:
      - "estilos/ursec-default-page.css"
      - "estilos/ursec-default.css"
      - "estilos/ursec-estilo.css"
    ## change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: true
## uncomment this line to produce HTML and PDF in RStudio:
#knit: pagedown::chrome_print
abstract: | 
  #### Informe de Mercado de Telecomunicaciones de Uruguay
  
  #### Datos a Diciembre 2020
  
  _Unidad Reguladora de Servicios de Comunicaciones (URSEC)_\
  Av. Uruguay 998 11000 Montevideo, Uruguay\
  Tel. +598 2902 8082\
  http://ursec.gub.uy
  
  
  **Presidenta**\
  Mercedes Aramendía
  
  **Vicepresidente**\
  Gustavo Delgado
  
  **Director**\
  Pablo Siris

  *División de Regulación Jurídica y Económica*\
  **Gerente**\
  Graciela Coronel\
  
  *Divisón de Servicios Postales*\
  **Gerente**\
  Luis González\

  Diseño de Portada: Enrique Ros\
  Foto de portada: Chan Lin (https://unsplash.com/@lowkeyhahaha)
  
  **Licencia Creative Commons**:
  
  **Compartir** Copiar y redistribuir materiales en cualquier medio o formato.
  **Adaptar** Remezclar transformar y construir sobre el material para cualquier propósito, inculos con fines comerciales. El licenciante no puede revocar estas libertades, siempre y cuando siga los términos de la licencia.
  **Atribución** Usted debe dar crédito de manera adecuada, brindar un enlace a la licencia, e indicar si se han realizado cambios. Puede hacerlo en cualquier forma razonable, pero no de forma tal que sugiera que usted o su uso tienen el apoyo de la licenciante.
  **Compartir Igual** Si remezcla, transforma o crea a partir del material, debe distribuir su contribución bajo la lamisma licencia del original.
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      message=FALSE,
                      cache=FALSE,
                      fig.width = 7, 
                      fig.height = 4.5)

source("setup.R", local = knitr::knit_global())

fig_height_small <- 4
fig_height_extra_small <- 3.5


partes <- c(
            '01-envios_postales.Rmd',
            '02-cartas_paquetes.Rmd',
            '03-tarifas_cartas.Rmd',
            '04-tarifas_paquetes.Rmd',
            '05-servicios_financieros.Rmd',
            '06-dimension.Rmd',
            '07-envios_por_habitante.Rmd',
            '08-ingresos.Rmd',
            '09-activos.Rmd')
```


```{r, child=partes}
```


# Índice de Gráficos  {.page-break-before}
```{r}
render_toc(partes)
```


<!-- Este hook le agrega .lof a las ultimos dos elementos .main -->
<!-- Para seleccionar  -->

```{js, echo=FALSE}
Paged.registerHandlers(class extends Paged.Handler {
  constructor(chunker, polisher, caller) {
      super(chunker, polisher, caller);
  }

  afterPreview(pages) {
    var pages = Array.from(pages).slice(-4);
    
    pages.forEach(function(page) {
      page.wrapper.classList.toggle("lof");
    });
    
  }
  
});
```